### ISSUE TITLE
aws_auth -  module 'botocore' has no attribute 'session'"

### ISSUE THREAD

**Issue by briantist** [ansible-collections/community.hashi_vault#167]
##### SUMMARY

Still investigating, but seeing issues of an unhandled exception with partial text:
>  module 'botocore' has no attribute 'session'"

When getting credentials via EC2 instance role. 

~This was likely introduced in #161 .~ This is actually caused by my using boto incorrectly. Trying to load the session via `botocore.session` only works if `boto3` was imported, so we should just use `boto3` for both the profile and session use cases. 

Before the [refactor](https://github.com/ansible-collections/community.hashi_vault/projects/4), both `boto3` and `botocore` were optionally imported with `try`/`except` regardless of whether they were used or not. After the refactor, the imports were moved into the conditionals so they were only loaded if needed, and then in the case of `botocore`, that broke things because `boto3` was no longer being loaded.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

_auth_method_aws_iam_login.py

##### ANSIBLE VERSION

N/A

##### COLLECTION VERSION

1.4.0

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Linux

##### STEPS TO REPRODUCE

```yaml
TBD
```

##### EXPECTED RESULTS

working to infer creds from EC2

##### ACTUAL RESULTS

```paste below
 module 'botocore' has no attribute 'session'"
```
